### ISSUE TITLE
Sensitivität der OCR Erkennung

### ISSUE THREAD

**Issue by erd82** [geimist/synOCR#13]
Hi zusammen, 

gibt es bei der OCR Erkennung eine Möglichkeit, die Sensitivität bei der Texterkennung zu erhöhen? Ich habe das Problem, dass gerade etwas hellere Texte nur schwer erkannt werden:
![image](https://user-images.githubusercontent.com/63564291/229311110-e82b34e7-60b5-4fa1-9fb0-9421820fde43.png)

Viele Grüße, erd

**Comment by geimist** [comment]
Du könntest zwei Dinge testen:
* In schwarz/weiß scannen statt in Graustufen
* Probiere mal das Image [geimist/ocrmypdf-polyglot_best](https://hub.docker.com/repository/docker/geimist/ocrmypdf-polyglot_best/general) (in der Docker-GUI laden und dann in synOCR deinem Profil zuweisen)

**Comment by erd82** [comment]
@geimist, danke für den Tipp! Docker Image eingespielt und probiert. Leider gibt es keine mir ersichtlichen Veränderungen / Verbesserungen. In schwarz/weiß scannen ist glaub bei vielen zu spät, da schon zu viele Dokumente digitalisiert sind.
