### ISSUE TITLE
Kompatibilität für Domänenuser ([Synology] Directory Server)

### ISSUE THREAD

**Issue by geimist** [geimist/synOCR#17]
Derzeit ist synOCR dafür ausgelegt, ausschließlich mit lokalen Benutzerkonten zusammenzuarbeiten. 
Um auch mit Domänenusern zu funktionieren, müsste die Berechtigungsfunktion umgebaut werden.

**Comment by toafez** [comment]
Hi!
Das Problem sollte durch diesen [PR](https://github.com/geimist/synOCR/pull/25) gelöst sein.

Gruß toafez

**Comment by geimist** [comment]
closed by #25
