### ISSUE TITLE
Wie stelle ich die Sprache der OCR-Engine ein – damit sie diakritische Zeichen korrekt erkennt?

### ISSUE THREAD

**Issue by lexybarton** [geimist/synOCR#18]
Können Sie mir bitte mitteilen, wie ich die Sprache von OCR ändern kann? Wenn das Quellbild diakritische Zeichen in tschechischer Sprache enthält, ist der resultierende Text voller Fehler und daher unbrauchbar.

<details>
  <summary>Sie können es bei Bedarf an diesem Bild selbst versuchen:</summary>

![cze-test](https://user-images.githubusercontent.com/14018895/230112675-8dde3131-250d-4cb4-b16b-46c1b0de7bf5.jpg)

</details>

Vielen Dank im Voraus für Ihre Hilfe

**Comment by geimist** [comment]
The language to be recognized is passed with the OCR parameters in synOCR GUI. 
The corresponding parameter is `-l <language>`. It is also possible to combine several languages by `+`. So in your case maybe `-l ces+eng`. 

* https://github.com/tesseract-ocr/tesseract/blob/main/doc/tesseract.1.asc#languages
* https://ocrmypdf.readthedocs.io/en/latest/languages.html

**Comment by lexybarton** [comment]
Thank you for your answer, and sorry for bothering, I should have find it.

**Comment by geimist** [comment]
No problem. There are no wrong questions. I'm happy if it works now 🙂

BTW:
I have one more quick question for you. Do you use the GUI of synOCR in Czech language? I would be interested to know how the quality of the automatic translation is?

**Comment by lexybarton** [comment]
👍 I wouldn't have guessed that. I really thought it was translated by a human...
