### ISSUE TITLE
Falsche Download Version! 

### ISSUE THREAD

**Issue by toafez** [geimist/synOCR#22]
Hi!
In der synOCR App wird mir die Version 1.3.2 zum Download angeboten, jedoch wird nach dem klick auf den Link die Version 1.3.1 geladen. Auch auf GitHub kann ich die Version 1.3.2 nicht herunterladen, sondern werde immer auf die Version 1.3.1 geleitet.

Gruß, toafez

**Comment by geimist** [comment]
Ich Drops hab die INFO nicht angepasst 🙈

Korrektur folgt ...
