### ISSUE TITLE
Falsche Download Version für DSM7

### ISSUE THREAD

**Issue by toafez** [geimist/synOCR#23]
Ich nochmal... sorry!

Für DSM6 kann ich jetzt die Version 1.3.3 downloaden, für DSM7 jedoch weiterhin die Version 1.3.1, egal ob über die synOCR App, GitHub bzw. deinem Server https://geimist.eu/synOCR/

Gruß toafez

**Comment by geimist** [comment]
Seit 11:38 Uhr müsste es die Version 1.3.3 laden. Ich hatte es extra gecheckt. Vielleicht ein Cacheproblem?

PS: du solltest auch auf ein geschlossenes Issue antworten können #22

**Comment by toafez** [comment]
Hat sich wohl irgendwie überschnitten! Kann jetzt die 1.3.3 für DSM7 laden. War wohl zu ungeduldig. Sorry.

Das ich auf einen geschlossenen Issue antworten kann, war mir nicht bewusst.
