### ISSUE TITLE
New setup not working

### ISSUE THREAD

**Issue by wjstone** [geimist/synOCR#33]
Whenever I run the script i get this error. 

/usr/syno/synoman/webman/3rdparty/synOCR/synOCR-start.sh: line 46: [: : integer expression expected

it fails everytime

**Comment by geimist** [comment]
Can you please check this version (you must unzip before install):
[synOCR_DSM7_local.spk.zip](https://github.com/geimist/synOCR/files/12607255/synOCR_DSM7_local.spk.zip)

**Comment by geimist** [comment]
Nothing was changed at this point for a long time. But good if it works now.

**Comment by geimist** [comment]
fixed in https://github.com/geimist/synOCR/commit/e360dddf5f70bcf284125077dd3b36288c5424b2
