### ISSUE TITLE
keine Verarbeitung von Scans mehr nach Update von 1.4.1 auf 1.4.5

### ISSUE THREAD

**Issue by exuded** [geimist/synOCR#45]
nach dem Update auf 1.4.5 werden Dokumente nicht mehr verarbeitet. Das Log schreibt nur: 

> `
>   ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
>   ● ---------------------------------- ●
>   ● |    ==> RUN THE FUNCTIONS <==   | ●
>   ● ---------------------------------- ●
>   ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
> 
>   -----------------------------------------------------------------------------------
>   | check the python3 installation and the necessary modules:                       |
>   -----------------------------------------------------------------------------------
> 
>                 prepare_python: OK
> Target temp directory:    /tmp/tmp.tvykkDvesg
> 
> 
>   ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
>   ● STEP 1 - RUN OCR / SPLIT FILES, IF NEEDED:                                      ●
>   ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
> 
> 
> ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
> CURRENT FILE:   ➜ Brother_1700W_12022024_000272.pdf
>                   temp. target file: /tmp/tmp.tvykkDvesg/step1_tmp_1707739154/Brother_1700W_12022024_000272.pdf
> 
>   -----------------------------------------------------------------------------------
>   | processing PDF @ OCRmyPDF:                                                      |
>   -----------------------------------------------------------------------------------
> `

und dann folgt seit 40 Minuten nichts mehr. 
Bereits versucht: Synology Restart, Docker Restart, synOCR Restart, manuelles entfernen der Dokumente aus dem Quellordner und wieder hinzufügen

**Comment by geimist** [comment]
Hat sich deine Anfrage erledigt?

**Comment by exuded** [comment]
Hallo, 
ich habe einfach festgestellt, dass die Verarbeitung sehr lange dauert. Sie funktioniert. Aber pro Dokument Dauer es ca 20-30 Minuten. Mag wohl an meiner älteren DS918+ liegen, auch wenn CPU und RAM dauerhaft unter 30% Auslastung sind…

**Comment by geimist** [comment]
Eigentlich sollte es bei weitem nicht so lange dauern. Aber es kommt natürlich auch auf die Größe der Dokumente an (viele hunderte Seiten). Auch zusätzliche OCR-Parameter könnten die Ausführungszeit verlängern, aber das wäre schon extrem bei dir.
Man könnte auch mal ein anderes Image probieren, aber prinzipiell arbeiten die da alle grundsätzlich gleich.

Minimaler RAM könnte bei vielen Seiten die Geschwindigkeit auch negativ beeinflussen. In dem Fall könnte man mit einem OCR-Paremter die Threadanzahl herabsetzen (z.B. auf 1 damit nur eine Seite gleichzeitig abgearbeitet wird).

**Comment by exuded** [comment]
Es sind maximal 4-5 Seiten pro Mehrseitigem Dokument. Die meisten Dokumente sind einseitig. Auch bei einseitigen Dokumenten dauert die Verarbeitung mehr als 15 Minuten. Diese Dokumente werden mit 300 DPI je Dokument gescannt.
Was kann ich für ein Debugging liefern? Die Log Dateien schreiben bisher keine Fehler. 
Was mit dem Absatz „Minimaler RAM […]“ gemeint ist verstehe ich nicht. Meine Synology hat 8 GB RAM und dieser wird bei weitem nicht ausgelastet von synOCR.

**Comment by geimist** [comment]
> Es sind maximal 4-5 Seiten pro Mehrseitigem Dokument. Die meisten Dokumente sind einseitig. Auch bei einseitigen Dokumenten dauert die Verarbeitung mehr als 15 Minuten.

Dann ist der Verarbeitungszeit erfahrungsgemäß zu lang. Aber du musst auch wissen, dass zunächst alle PDFs geocrd werden und anschließend die Tagerkennung durchlaufen wird. Erst nach dem zweiten Schritt erscheinen die einzelnen PDFs im Zielordner. Bei vielen PDFs dauert es also, bis erste Ergebnisse im Ausgabeverzeichnis zu sehen sind.   

Du kannst mir gern privat ein Log von einer einzelnen PDFschicken ([Upload](https://geimist.eu/synOCR/_synOCR_userupload.html)).




> Was mit dem Absatz „Minimaler RAM […]“ gemeint ist verstehe ich nicht. Meine Synology hat 8 GB RAM …

Da ist das nicht die Ursache.
