### ISSUE TITLE
Metadata-Datei im Ausgabe-Ordner

### ISSUE THREAD

**Issue by socram70** [geimist/synOCR#46]
Mit dem Erstellen der OCR-Version der PDF wird außerdem auch eine .metadata-Datei angelegt, die einige Metadaten enthält. Das finde ich eher störend und wird von mir nicht benötigt. Ich habe keine Option gefunden, um das Verhalten zu deaktivieren. Gibt es hierfür eine Lösung?

Der Inhalt der Datei sieht in etwa so aus:
#Wed Feb 28 15:11:32 CET 2024
file.ocrstatus=10
file.principal=
file.name=2024-02-20_.pdf
file.size=4316852
file.source=zentraler Scanordner

**Comment by geimist** [comment]
Ganz sicher, dass das synOCR die Ursache ist? Das ist mir völlig neu. 

- In welchem Verzeichnis liegt sie und was ist der Zeitstempel des Erstellzeitpunktes? (Zeitpunkt des Scannens oder des Abarbeitens von synOCR?)
- Wird diese Datei auch erstellt, wenn du eine bestehende Datei aus dem Backupverzeichnis in das Quellverzeichnis kopierst?

**Comment by socram70** [comment]
Das ging schnell, danke! Ich habe mich auch sehr gewundert, weil ich hierzu nichts in der Dokumentation oder sonstwo gefunden habe. Es ist genauso gut möglich, dass ocrmypdf die Dateien erstellt, es ist aber schon merkwürdig, dass das offenbar nur bei mir der Fall ist.

Zuvor fiel mir auf, dass synOCR gar nicht mehr lief (weil ich eine alte Version hatte, die ich noch über den Paketmanager installiert hatte), sodass es ich es sauber deinstalliert und über die .spk-Datei von hier installiert habe.

Zu deinen Fragen:
1. Die Datei liegt zusammen mit den anderen Dateien im Ausgabeverzeichnis und der Zeitpunkt ist identisch mit dem Datum der zugehörigen abgearbeiteten PDF.
2. Ja

Interessant ist auch, dass die Datei neu erstellt wird, sobald man sie löscht. Mir würde keine andere Software einfallen, die auf den Ordner Zugriff hat und dies verursachen könnte.

**Comment by geimist** [comment]
> Zuvor fiel mir auf, dass synOCR gar nicht mehr lief (weil ich eine alte Version hatte, die ich noch über den Paketmanager installiert hatte), sodass es ich es sauber deinstalliert und über die .spk-Datei von hier installiert habe.

Du hättest vorher nicht deinstallieren müssen 😉

Wer ist der Eigentümer dieser Datei?
synOCR arbeitet immer in temporären Ordnern und dann gibt es Routinen, die die fertige Ausgabedatei handeln. Würde diese Datei von von OCRmyPDF stammen, dann müsste synOCR diese 'bewusst' in das Zielverzeichnis legen. Andernfalls würde alles im temporären Ordner nach dem Abschluss verworfen und mit dem temporären Ordner gelöscht.

Da sie auch neu erstellt wird, wenn sie manuell gelöscht wird, lässt mich auch auf einen externen Mechanismus schließen.

Wo kommt in deiner Umgebung so ein Begriff wie "zentraler Scanordner" (Wert `file.source`) vor?

**Comment by socram70** [comment]
Oh man, das ist mir nun etwas peinlich, aber tatsächlich stammt die Datei von einer anderen Software, an die ich gar nicht mehr gedacht hatte.

Gut zu wissen mit der Deinstallation und vielen Dank für deine nette Rückmeldung. Entschuldige die Zeitverschwendung und danke für deinen Einsatz!

**Comment by geimist** [comment]
Kein Problem. Kannst du noch sagen, um welche Software es sich handelt? Ich hatte jetzt im Acronis Forum [etwas dazu entdeckt](https://forum.acronis.com/comment/523647#comment-523647).

**Comment by socram70** [comment]
Klar, ich hatte das weggelassen, weil das sicher niemand außer mir benutzt. Die Datei werden von einer Beta-Version von j-lawyer angelegt, die Software für Rechtsanwälte, die ich benutze und die ebenfalls den Scan-Ordner auf neue Dateien prüft.
