### ISSUE TITLE
Bitte Meta-Data files aus spk files entfernen

### ISSUE THREAD

**Issue by hgy59** [geimist/synOCR#49]
Die im Release Bereich zur Verfügung gestellen spk Dateien enthalten unnötige Meta-Daten Files.

Es handelt sich um "meta-data" Dateien von "Mac  OS X".

Zusätzlich zu `.DS_STORE` git es zu jeder Datei im spk file und auch im enthaltenen package archiv (package.tgz) eine Datei mit dem prefix `._`.

Dieser Fehler besteht seit synOCR Version 1.4.0, bei 1.3.3 war alles noch in Ordnung.

Wenn mit `build_spk.sh` ein package erstellt wird, sind keine solchen Datein im spk file enthalten, auch nicht wenn solche im PKG_DSM7 oder PKG_DSM6 Verzeichnis existieren.

Hab keine Ahnung, wie die Release spk Files erstellt werden, aber irgendwie ist ein OS X System beteiligt, das diese meta data Files mit einpackt.

Auszug aus output von `7z l  synOCR_DSM7_v1.4.5.spk `
```
...
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2023-09-26 12:00:03 .....          163          512  ._CHANGELOG
2023-09-26 12:00:03 .....        15746        15872  CHANGELOG
2023-09-26 12:00:04 .....          163          512  ._INFO
2023-09-26 12:00:04 .....        14391        14848  INFO
2023-09-26 12:00:03 .....          163          512  ._LICENSE
2023-09-26 12:00:03 .....        35559        35840  LICENSE
2023-09-26 12:00:03 .....          163          512  ._PACKAGE_ICON.PNG
2023-09-26 12:00:03 .....         8686         8704  PACKAGE_ICON.PNG
2023-09-26 12:00:03 .....          163          512  ._PACKAGE_ICON_120.PNG
2023-09-26 12:00:03 .....        15932        16384  PACKAGE_ICON_120.PNG
...
```

**Comment by geimist** [comment]
Ich hatte anfangs die Pakete direkt im Synology DSM gebaut. Vor einigen Versionen hatte ich das Buildscript dann so angepasst, dass es flexibler auf unterschiedlichen Umgebungen genutzt werden kann. Und ja: ich baue das SPK auf einem Mac. Mir ist das bisher noch nicht aufgefallen, weil ich die Files / Ordner halt nicht sehe und meines Wissens bereiten sie auch keine Probleme. Aber ich werde mir das Buildscript nochmal ansehen, damit diese versteckten Ordner nicht mit im Paket landen.

**Comment by hgy59** [comment]
Ich kann in meinem fork unter linux den Fehler mit dem parameter -v=local und --dsm=7 reproduzieren, wenn ich solche files ins PKG_DSM7 Verzeichnis stelle.
Die werden mit dem Fix in #50 nicht mehr hinzugefügt.

> Wenn mit build_spk.sh ein package erstellt wird, sind keine solchen Datein im spk file enthalten, auch nicht wenn solche im PKG_DSM7 oder PKG_DSM6 Verzeichnis existieren.

Für obige Bemerkung habe ich folgende Erklärung:
Ohne version Parameter (oder mit version != local) kann ich das unter Linux nicht testen, weil ein temp. git worktree verwendet wird.

Übrigens kann ich in meinem local fork mit dem script keine offizielle Version bilden, weil die tags fehlen.
