### ISSUE TITLE
Vereinfachung der Dokumentation (Repos, Links, ...)

### ISSUE THREAD

**Issue by erd82** [geimist/synOCR#5]
Hi Stephan,

letztes Jahr bin ich auf dein Projekt gestoßen und hatte es schon einmal auf meiner Synology (DSM7) eingerichtet - Verison 1.1.902. 
Ein tolles Projekt übrigens (nachdem ich immer gesucht hatte, Netzwerkscanner + Synology, die die PDFs nachbearbeitet). Mich würde mal interessieren, wie viele Leute das Projekt erfolgreich nutzen.

Ich selbst bin jedoch nach der ersten Installation leider irgendwann stecken geblieben, da ich nicht ausreichend Zeit fand, ausreichend Regeln für den praktischen Einsatz zu konfigurieren.

Nun wollte ich gern einen neuen Anlauf nehmen und wollte eine derzeitige Version aktualisieren.

1. Übers Web bin ich erstmal https://git.geimist.eu/geimist/synOCR gestoßen.  Dort sehe ich, dass die Files erst kürzlich aktualisiert wurden, das Repo sich jedoch nach Github verschoben hat. Ist dies korrekt?
![image](https://user-images.githubusercontent.com/63564291/228104928-45acfc26-e2d3-404a-b33f-e234eacf8495.png)

2. Wenn ich auf Github gehe, verweisen zahlreiche Links im beschreibenden Wiki weiterhin auf geimist.eu. Das führt leider zu einer Kreisverlinkung, was leider etwas verwirrend erscheint.

3. Auf der Github Seite finde ich erstmal nur die Version 1.2.0.
![image](https://user-images.githubusercontent.com/63564291/228107737-14a54aa3-c764-40cd-a632-f1a00e31f281.png)
In der Github Installationsanleitung wird von der Version 1.3.0 und höher gesprochen. Folge ich dem Link mit der [Entwicklerseite](https://geimist.eu/synOCR/), dann werde ich final fündig.

Wäre es vielleicht möglich die Dokumentation bzw. die Verteilung des Repos (über geimist.eu und Github) etwas zu verschlanken? Das würde vielleicht den Einstieg oder das erneute Einlesen in die Installation für viele vereinfachen.

Viele Grüße

**Comment by geimist** [comment]
> Mich würde mal interessieren, wie viele Leute das Projekt erfolgreich nutzen.

Mich auch 😉
Für eine genaue Aussage müsste ich aber die Installationen tracken, was nicht jedem – wenn auch anonymisiert – recht sein wird. Anhand des Updatechecks kann ich aber davon ausgehen, dass es sich um einen vierstelligen Bereich handelt.

> 1. Übers Web bin ich erstmal https://git.geimist.eu/geimist/synOCR gestoßen.  Dort sehe ich, dass die Files erst kürzlich aktualisiert wurden, das Repo sich jedoch nach Github verschoben hat. Ist dies korrekt?

Bisher war das Repo auf meinem [Server](https://git.geimist.eu/geimist/synOCR) gehostet, wurde aber schon lange nach Github gespiegelt. Ein entscheidenter Nachteil war, dass es anderen Usern so schwer war, PRs einzureichen, es sei denn, ich habe ihnen ein eigenes Konto eingerichtet. Vor rund zwei Wochen habe ich dann den Sync zwischen Gitea und Github aufgehoben und führe die Entwicklung auf Github fort. Das Repo auf meinem Server bleibt aber vorerst erreichbar, weil es noch einige Codeverlinkungen im Forum gibt, die ich nicht ändern kann.

> 2. Wenn ich auf Github gehe, verweisen zahlreiche Links im beschreibenden Wiki weiterhin auf geimist.eu. Das führt leider zu einer Kreisverlinkung, was leider etwas verwirrend erscheint.
> 

Danke, habe ich jetzt versucht zu korrigieren. Ich hatte da noch nicht alles durchgesehen, weil die Links ja nicht falsch aufgelöst wurden.

> 3. Auf der Github Seite finde ich erstmal nur die Version 1.2.0.

Leider werden bei einem Sync zwischen Gitea und Github die Releases nicht mit abgeglichen. Das werde ich jetzt auch nicht nachholen. Zukünftige Releases werden natürlich in der entsprechenden Kategorie eingepflegt. Das letzte Release habe ich jetzt mal mit aufgenommen. Das ist sicherlich weniger verwirrend.

Vielen Dank für dein Feedback
