### ISSUE TITLE
Unterstützung von textuellen Datumsformat

### ISSUE THREAD

**Issue by erd82** [geimist/synOCR#6]
Hi Stephan,

die automatische Datumserkennung ist wirklich ein großartiges Feature und in meinen Augen ein Game-Changer! (im Vergleich zu vor einem Jahr). Denn genau das kostet bei der Digitalisierung und Umbenennen von Dokumenten sehr viel Zeit.

Wenn im Dokument das Format TT.MM.JJJJ (z.B. 13.04.2023) verwendet wird, funktioniert das Feature bei mir derzeit fabelhaft!

Wenn jedoch das Datumsformat TT. MMM JJJJ (z.B. 13. Okt 2023) oder TT. MMMM JJJJ (z.B. 13. Oktober 2023) vorliegt, wird derzeit das Datum nicht erkannt und es wird lediglich das Datum des Dokuments verwendet.
![image](https://user-images.githubusercontent.com/63564291/228320331-df688f35-ef31-4e6b-bc4c-1b61fd6c8f18.png)

Ist es geplant, dieses Datumsformat auch zu erkennen?

Viele Grüße

**Comment by geimist** [comment]
Welche synOCR Version nutzt du?
Auf dem ersten Blick sieht es auch so aus, als ob du nur mit der internen RegEx-Suche suchst, aber nicht mit dem Pythonmodule.

**Comment by erd82** [comment]
ich verwende die Version 1.3.1. Und ja du hast Recht, ich verwende aktuell die RegEx-Suche laut GUI:
![image](https://user-images.githubusercontent.com/63564291/228323888-72e3755c-88ac-4367-b65b-0f65f9226172.png)

Also würdest du empfehlen auf Python umzustellen? Ist dies schon irgendwo dokumentiert? Vielleicht hätte ich da auch selbst drauf stoßen können :-). Grüße

**Comment by erd82** [comment]
Mmmh, aus irgendeinem Grund läuft er bei mir in einen Fehler. 
![image](https://user-images.githubusercontent.com/63564291/228325920-cad2158f-637d-49e7-9ac6-0d841cdc3ef0.png)

Hast du eine Idee?

**Comment by geimist** [comment]
Kannst du mir mal [bitte ein komplettes Log schicken](https://geimist.eu/synOCR/_synOCR_userupload.html)?

**Comment by erd82** [comment]
Habs dir hochgeladen. Ist das komplett bzw. ausreichend?

**Comment by geimist** [comment]
Ja, ist da - aber lässt mich grübeln ... 🤔
An so einen Fehler kann ich mich die letzten Monate auch nicht wirklich erinnern (ist ja auch nicht gerade sehr aussagekräftig).
Hättest du mal ein Testfile?

**Comment by erd82** [comment]
Ich hab dir mal ein Test-File hochgeladen, welches aktuell zum gleichen Ergebnis führt.
Zudem hab ichs jetzt mit log level 2 durchgeführt und dir auch das log hochgeladen.

**Comment by geimist** [comment]
Loglevel 2 war schon besser.
Kannst du mir mal bitte deinen Pfad zum Logordner schreiben?

**Comment by erd82** [comment]
Das ist der Log-Ordner: /volume1/data/# Document Inbox/# synOCR/Log

Was mir auch auffällt, dass nach der Umstellung auf Python die RegEx Regeln (also Verschiebung, Umbenennung) nicht mehr funktionieren.

Und kann es einen Einfluss haben, dass ich gestern lediglich die neuere Version (1.3.1) über die damalige Version 1.1.902 drüber installiert habe? Gibt es vielleicht noch ungewollte (alte) Einstellungen?

**Comment by geimist** [comment]
Das Update sollte kein Problem sein. Ich vermute, dass uns hier die Raute `#` im Pfad ärgert. Wäre es ein großer Aufwand, das mal zu checken? (Vielleicht nur mal das aktuelle Profil clonen und zum Test einen anderne Quell- und Logpfad setzen).

@Gthorsten65 kann es sein, dass es hier ein Problem bei der Übergabe der Parameter gibt?
````

  -----------------------------------------------------------------------------------
  | search for a valid date in ocr text:                                            |
  -----------------------------------------------------------------------------------

ERROR at line 1007: founddatestr=$( python3 ./includes/find_dates.py -fileWithTextFindings "$searchfile" $arg_searchnearest -dateBlackList "$ignoredDate" -dbg_file $current_logfile -dbg_lvl "$loglevel" -minYear "$minYear" -maxYear "$maxYear" 2>&1)
                find_dates.py result:
                usage: find_dates.py [-h] [-fileWithTextFindings FILEWITHTEXTFINDINGS]
                                     [-dateBlackList DATEBLACKLIST]
                                     [-searchnearest SEARCHNEAREST] [-dbg_file DBG_FILE]
                                     [-dbg_lvl {0,1,2}] -minYear MINYEAR -maxYear MAXYEAR
                find_dates.py: error: unrecognized arguments: Document Inbox/# synOCR/Log/synOCR_2023-03-28_20-19-58.log
                ERROR at line 1007: python3 ./includes/find_dates.py -fileWithTextFindings "$searchfile" $arg_searchnearest -dateBlackList "$ignoredDate" -dbg_file $current_logfile -dbg_lvl "$loglevel" -minYear "$minYear" -maxYear "$maxYear" 2>&1
```

**Comment by Gthorsten65** [comment]
@geimist Hmm,  hast du mal den Python teil des log files?
Kann aus deinem post nicht erkennen wie die Parameter sind.
Im logile, also das was ich logge, sollte alle drin stehen.
Welcher Parameter hat denn ein#? Kann das mal ausprobieren

**Comment by geimist** [comment]
Das ist ja dein Log Part. Du gibst nur die Hilfe zurück. 
Aber dadurch, dass eine Raute im Pfad ist und ich den Pfad unmaskiert übergebe, wird der Aufruf vor der Raute enden und du bekommst ein ungültiges Parameterset. Das wäre für mich jetzt die naheliegendste Ursache.

**Comment by geimist** [comment]
Schön und nicht schön - aber Fehler gefunden. Das ist gut. Funktionieren die Regeln beim Test wieder? Eigentlich sollte die Umstellung auf die Pythonsuche damit nichts zu tun haben.

**Comment by Gthorsten65** [comment]
Habe gerade mal geschaut. So wie Du den lognamen übergibst geht das nicht. Das sieht das Pythonscript als mehrere Parameter.
Es sind Leerzeichen vorhanden.
Dann musst du das in "" oder '' setzen.

**Comment by erd82** [comment]
> Schön und nicht schön - aber Fehler gefunden. Das ist gut. Funktionieren die Regeln beim Test wieder? Eigentlich sollte die Umstellung auf die Pythonsuche damit nichts zu tun haben.

Ich hab auch noch mal hin und her getestet. Du hattest Recht! Ich hatte wohl in meiner Regeldatei einen Typo drin, sodass die Regeln nicht mehr gezogen haben. Also das Datums-Problem ist wohl lediglich durch die Raute im Pfad verursacht.

**Comment by geimist** [comment]
Korrekt, das mache  ich eigentlich auch schon aus Prinzip. Ist hier wohl verloren gegangen und keiner hat's gemerkt 🙈

> Wie oben beschrieben funktionieren nach der Umstellung auf Python die Regeln nicht mehr (vielleicht auch ein wichtiger Hinweis).

Im originalen Profil wird deine Krankenkasse gefunden. Im geclonten gibt es Fehlermeldungen, die ich jetzt gerade auch nicht zuordnen kann.

[Hier ist eine BETA](https://geimist.eu/synOCR/special/synOCR_DSM7_local_BETA.spk), die diesen Fehler fixen sollte. bitte checke mal, ob mit dem default Profil auch wieder die Regeln funktionieren.

**Comment by erd82** [comment]
> > Wie oben beschrieben funktionieren nach der Umstellung auf Python die Regeln nicht mehr (vielleicht auch ein wichtiger Hinweis).

Ja wie gesagt war das mein Fehler. Ich hatte einen Typo in der Regeldatei.

> [Hier ist eine BETA](https://geimist.eu/synOCR/special/synOCR_DSM7_local_BETA.spk), die diesen Fehler fixen sollte. bitte checke mal, ob mit dem default Profil auch wieder die Regeln funktionieren.

Die Beta habe ich installiert und das Monitoring neu gestartet (müsste doch reichen oder?).
Leider wird das Datum noch nicht korrekt verarbeitet. Aber könnte es an den zwei Rauten im Pfad (sowohl für Logs als auch für Input/Output Ordner) liegen?

**Comment by geimist** [comment]
Dazu bräuchte ich wieder das Log, bzw. den unmittelbaren Teil ab hier:
```
  -----------------------------------------------------------------------------------
  | search for a valid date in ocr text:                                            |
  -----------------------------------------------------------------------------------
```

**Comment by Gthorsten65** [comment]
Genau das würde helfen

**Comment by erd82** [comment]
habs Stephan hochgeladen. Aber auch hier der direkte Abschnitt:
![image](https://user-images.githubusercontent.com/63564291/228342750-10154603-9972-4800-ad83-44a68705883c.png)

**Comment by geimist** [comment]
Du hast die Standardregexsuche aktiv (bist glaube auch in deinem Testprofil) 😉

**Comment by erd82** [comment]
Ich habe wieder mein Default Profil laufen, extra nochmal das Monitoring neu gestartet.
Und weiterhin läuft die Datumssuche mittels Python.
![image](https://user-images.githubusercontent.com/63564291/228343669-f1febe5f-6bed-4788-aeb7-34fce1aac00c.png)

Im Ergebnis kommt leider noch das falsche Datum heraus:
![image](https://user-images.githubusercontent.com/63564291/228343849-95a7b22c-f754-486d-8abe-8e12eaf49c8a.png)

**Comment by geimist** [comment]
Bitte ein Log 😃

**Comment by erd82** [comment]
Hab dir das Log hochgeladen (mache dann nur noch einen Daumen auf deinen Comment, wenn ich es hochgeladen habe, Dann bläht es die Konversation nicht weiter auf).

Explizites Speichern des Profils werde ich noch mal versuchen. Da ich aber nicht mehr das Profil (Methode der Datumsuche) geändert habe, schließe ich das nahezu aus. Aber ein Versuch ist es Wert :).

**Comment by erd82** [comment]
Absolut korrekt ! Das Problem sitzt wohl manchmal vorm Rechner ! :-o
Ich hatte beide Profile verwechselt und dachte, ich arbeite im anderen Profil.

Jetzt hat es super funktionier 👍.

**Comment by geimist** [comment]
Datum da?

**Comment by erd82** [comment]
Jap, funktioniert jetzt korrekt und das Datum ist da 👍.
Ich habe gerade auch mal mit anderen Dokumente getestet, die einen textuellen Monat hatten. Hat auch bisher super geklappt bei allen fünf Versuchen. :)

TOP!

**Comment by erd82** [comment]
cool, ganz vielen Dank für den Fix und die neue Version ! Ich habe sie gleich installiert 👍. Merci & viele Grüße
