### ISSUE TITLE
Default Profil zurückgesetzt nach Löschen eines anderen Profils

### ISSUE THREAD

**Issue by erd82** [geimist/synOCR#7]
Hi Stephan,

ich vermute, ich bin auf einen schwerwiegenden Bug gestoßen: Wenn ich ein Profil clone und dann den Clone lösche, ist auch das Default Profil komplett zurückgesetzt.

Das Problem scheint sich nicht nur auf Clones zu beziehen. Auch ein das Löschen eines unabhängig erstellten Profils führt zum Zurücksetzen des Default Profils.

Viele Grüße

**Comment by geimist** [comment]
Du musst lediglich mal die Seite neu laden. Dann siehst du, dass alle Einstellungen des default-Profils noch vorhanden sind.

**Comment by erd82** [comment]
aaaah ok ... ich werde da ja mal nicht weiter testen und ausprobieren, da ich erste produktive Profile aufsetze und sie hoffentlich erhalten bleiben :-).

**Comment by geimist** [comment]
Das würde mich schon stark wundern, wenn das jahrelang nicht aufgefallen wäre. Aber es soll ja dir skurrilsten Dinge geben. Mache aber am besten regelmäßig eine Sicherung mit HyperBackup von synOCR (oder lade dir die Datenbank herunter).
